* 数据对齐
* 时间序列
* 时间序列，和非时间序列
* 数学运算
* 灵活处理确实数据
* 合并

In [47]:
from pandas import Series,DataFrame
import pandas as pd
import numpy as np

# pandas 数据结构介绍
## Series

In [2]:
obj = Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [11]:
# 指定索引的初始化
# 类似 dict
obj2 = Series([4,7,-5,3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [12]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [13]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [15]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [18]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [19]:
# 类似dict的操作
'b' in obj2

True

In [21]:
sdata = {'Ohio':35000, 'Texas': 71000, 'Oregon':16000, 'Utah':5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [28]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)
#obj4
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [31]:
# isnull 判断是否有数据缺失
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [36]:
obj4.name = 'population'
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [37]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrame

> 表格型数据类型，行索引，列索引，由Series组成的字典

In [48]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]
       }
frame = DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [49]:
# 指定列序列
DataFrame(data, columns=['year','state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [50]:
# 指定列，没有，则为NA值
# 指定 index 值
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                  index = ['one', 'two', 'three', 'four', 'five']
                  )
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [51]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [52]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [53]:
frame2.ix['three']

/Users/cuijl/.pyenv/versions/3.6.0/envs/rqalpha_3.6.0/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [55]:
# 列赋值
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [61]:
frame2['debt'] = np.arange(5)
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [62]:
# 指定索引列赋值
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [68]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [69]:
# del 删除列的值
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

> 通过索引返回的列只是相应的试图而已，并不是副本，想获取副本，使用`copy()`函数

In [71]:
# 嵌套字典
pop = {
    'Neada': {2001: 2.4, 2002:2.9},
    'Ohio': {2000:1.5, 2001:1.7, 2002:3.6}
}
frame3 = DataFrame(pop)
frame3

Neada  Ohio
2000    NaN   1.5
2001    2.4   1.7
2002    2.9   3.6

In [72]:
# 转置
frame3=  frame3.T

In [73]:
frame3

2000  2001  2002
Neada   NaN   2.4   2.9
Ohio    1.5   1.7   3.6

[![FktDGF.md.png](https://s1.ax1x.com/2018/11/25/FktDGF.md.png)](https://imgchr.com/i/FktDGF)

In [75]:
# 返回 df 二维ndarray
frame3.values

array([[nan, 2.4, 2.9],
       [1.5, 1.7, 3.6]])

## 索引对象

In [77]:
obj = Series(range(3), index = ['a', 'b', 'c'])
index = obj.index
index  # index 值具有不可修改性

Index(['a', 'b', 'c'], dtype='object')

[![FktHsA.md.png](https://s1.ax1x.com/2018/11/25/FktHsA.md.png)](https://imgchr.com/i/FktHsA)

## 重新索引

In [78]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b','a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [79]:
# reindex 将根据新索引进行重排
obj2 = obj.reindex(['a', 'b', 'c', 'd'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

In [80]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value = 0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [85]:
## 前向值填充
"""
对于停牌的股票，
根据时间序列，前向值填充
"""

obj3 = Series(['blue', 'purple', 'yellow'], index = [0,2,4])
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

|参数|说明|
|----|----|
|ffill 或 pad| 前向填充|
|bfill 或者 backfill| 后项填充|

In [87]:
# 指定行，指定列
frame = DataFrame(
    np.arange(9).reshape((3,3)),
    index = ['a', 'b', 'c'],
    columns = ['Ohio', 'Texas', 'California']
)
frame


Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [88]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN

[![FkshnS.md.png](https://s1.ax1x.com/2018/11/25/FkshnS.md.png)](https://imgchr.com/i/FkshnS)

## 丢弃指定轴上的项

In [90]:
obj = Series(np.arange(5), index=['a','b','c','d','e'])
# 丢弃指定轴
new_obj = obj.drop('c')
new_obj

a    0
b    1
d    3
e    4
dtype: int64

In [91]:
obj.drop(['d', 'c'])

a    0
b    1
e    4
dtype: int64

In [92]:
data = DataFrame(np.arange(16).reshape((4,4)), 
                index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                columns = ['one','two', 'three', 'four']
                )
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [94]:
# 删除指定行
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [95]:
# 删除指定列
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [97]:
data.drop(['two', 'four'], axis =1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

## 索引，选取和过滤

In [98]:
obj = Series(np.arange(4), index=['a', 'b','c', 'd'])
obj

a    0
b    1
c    2
d    3
dtype: int64

In [101]:
# Series的索引值不只是整数
obj['b']

1

In [102]:
obj[1]

1

In [103]:
obj[2:4]

c    2
d    3
dtype: int64

In [104]:
obj[['b','a','c']]

b    1
a    0
c    2
dtype: int64

In [106]:
obj['b':'c'] # 包含关系

b    1
c    2
dtype: int64

In [117]:
"""
对DataFrame 进行索引其实就是获取一个或者多个列
"""
data = DataFrame(
    np.arange(16).reshape((4,4)),
    index = ['Ohio', 'Colorado', 'Utah', 'New York'],
    columns = ['one', 'two', 'three', 'four']
)
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [118]:
# 列索引
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [115]:
# 多列索引
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [137]:
# 切片
data[:1]

one  two  three  four
Ohio    0    1      2     3

In [138]:
data['one'][3]

12

In [140]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [141]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [145]:
data.ix[['Colorado', 'Utah'], [3,0,1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

## 算数运算和数据对齐

In [146]:
# 并集
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'b', 'd', 'e'])
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c','e', 'f', 'g'])
s1

a    7.3
b   -2.5
d    3.4
e    1.5
dtype: float64

In [147]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [148]:
s1 + s2

a    5.2
b    NaN
c    NaN
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [149]:
df1 = DataFrame(
    np.arange(9).reshape((3,3)),
    columns = list('bcd'),
    index = ['Ohio', 'Texas', 'Colorado']
)
df2 = DataFrame(
    np.arange(12).reshape((4,3)),
    columns = list('bde'),
    index = ['Utah', 'Ohio', 'Texas', 'Oregon']
)
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [151]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [152]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

## 算术方法中填充值

In [154]:
df1 = DataFrame(np.arange(12).reshape((3,4)), columns=list('abcd'))
df2 = DataFrame(np.arange(20).reshape((4,5)), columns=list('abcde'))
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [155]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [156]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [157]:
# 填充默认值
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [160]:
# 重新索引指定 默认值
df1.reindex(columns=df2.columns, fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

|方法|说明|
|----|---|
|add | 加法|
|sub|减法|
|div|/|
|mul| 乘法|

## DataFrame 和 Series 之间运算

In [161]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [164]:
arr = -arr[0]

In [165]:
arr

array([ 0, -1, -2, -3])

In [166]:
arr - arr[0]

array([ 0, -1, -2, -3])

In [174]:
frame = DataFrame(
    np.arange(12).reshape((4,3)), 
    columns=list('bde'), 
    index = ['Utah', 'Ohio', 'Texas', 'Oregon']
)
"""
ix可以通过行号和行标签进行索引，而iloc只能通过行号索引，
即ix可以看做是loc和iloc的综合。
"""
series = frame.iloc[0]

In [179]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

### loc -- 通过行标签索引行数据

* loc 只能通过行标签进行行索引
   ` frame.loc[['Utah','Texas']]`

* loc[‘d’]表示索引的是第’d’行（index 是字符）
`frame.loc['Texas']`

* loc扩展--索引某行某列
`frame.loc['Texas', 'e']`
    
* loc扩展--索引某列
`frame.loc[:,['b']]`
   
###  iloc -- 通过行号获取数据

* 想要获取哪一行
`frame.iloc[1]`

* 行标签不可以

* 同样通过行号可以索引多行
`frame.iloc[[1,2]]`

* iloc 索引列数据
`frame.iloc[:, [2]]`

###  `ix -- 结合前两种的混合索引
* 通过行号索引
`frame.ix[1]`

* 通过行标签索引
`frame.ix['Ohio']`

参考：
[Pandas——ix vs loc vs iloc区别](https://blog.csdn.net/Xw_Classmate/article/details/51333646)

## 函数应用和映射

In [208]:
frame = DataFrame(np.random.randn(4,3), columns=list('bde'), 
                 index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    0.094289 -1.127835 -0.085474
Ohio   -1.575873  1.208490  0.330717
Texas  -0.654419  0.268351 -1.376096
Oregon -0.314220  0.402282 -0.716094

In [210]:
# 绝对值
np.abs(frame)

b         d         e
Utah    0.094289  1.127835  0.085474
Ohio    1.575873  1.208490  0.330717
Texas   0.654419  0.268351  1.376096
Oregon  0.314220  0.402282  0.716094

In [211]:
# 使用 apply 将函数应用到 各列或者 行所形成一维数组上。
f = lambda x : x.max() - x.min()
# 默认各列
frame.apply(f)

b    1.670162
d    2.336324
e    1.706813
dtype: float64

In [213]:
# 应用到各行
frame.apply(f, axis=1)

Utah      1.222124
Ohio      2.784362
Texas     1.644447
Oregon    1.118377
dtype: float64

In [216]:
# 返回多个值
def f(x):
    return Series([x.min(), x.max(), x.sum()], index=['min', 'max', 'sum'])
# 对每一列进行 min , max, sum 计算
frame.apply(f)

b         d         e
min -1.575873 -1.127835 -1.376096
max  0.094289  1.208490  0.330717
sum -2.450222  0.751288 -1.846947

In [220]:
# 将各个浮点值得格式化字符串
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah     0.09  -1.13  -0.09
Ohio    -1.58   1.21   0.33
Texas   -0.65   0.27  -1.38
Oregon  -0.31   0.40  -0.72

In [223]:
# Series 有 map函数
frame['e'].map(format)

Utah      -0.09
Ohio       0.33
Texas     -1.38
Oregon    -0.72
Name: e, dtype: object

## 排序和排名

In [226]:
obj = Series(range(4), index=['d', 'a', 'b', 'c'])
# 索引排序
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [227]:
frame = DataFrame(
    np.arange(8).reshape((2,4)),
    index=['three', 'one'],
    columns = ['d', 'a', 'b', 'c']
)
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [229]:
# 按索引排序
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [230]:
# 对列标签排序
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [233]:
# 降序排序
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [235]:
# 对多个列进行排序
frame = pd.DataFrame({
    'b': [4,7,-3, 2],
    'a': [0,1,0,1]
})
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [237]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [238]:
frame.sort_values(by=['a', 'b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [240]:
# 排名
obj = Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [241]:
# 原数据中出现的顺序给出排名
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [242]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

## 带有重复值得轴索引