In [1]:
import numpy as np

### 并行思想

In [2]:
normal_list = range(10000)
%timeit [i**2 for i in normal_list]

3.13 ms ± 67.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
np_list = np.arange(10000)
%timeit np_list**2

5.05 µs ± 13.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
np_list = np.ones(5) * 3
np_list

array([3., 3., 3., 3., 3.])

## 初始化操作

In [6]:
np.zeros_like(np_list)

array([0., 0., 0., 0., 0.])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#help(np.linspace)
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [10]:
stock_cnt = 200
view_days = 504
stock_day_change = np.random.standard_normal((stock_cnt, view_days))
print(stock_day_change.shape)

(200, 504)


In [12]:
stock_day_change[1:3,:5]

array([[ 0.71827589, -0.05631482, -0.86201441,  0.37221116,  1.64599885],
       [-0.37151912, -0.5288521 , -0.11004535,  0.62285677, -0.38155622]])

In [13]:
stock_day_change[:2,:5] > 0.5

array([[ True, False, False, False,  True],
       [ True, False, False, False,  True]])

In [15]:
mask = stock_day_change[:2,:5] > 0.5
tmp_test = stock_day_change[:2,:5].copy()
tmp_test[mask]

array([1.20675641, 1.2620816 , 0.71827589, 1.64599885])

### 通用序列公式